<?xml version="1.0" encoding="utf-8"?><Database Name="kbs2" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=176.31.253.42,119;Initial Catalog=kbs2;User ID=jonaham" SettingsObjectName="PetjeOp.Properties.Settings" SettingsPropertyName="kbs2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.answer" Member="tblAnswers">
    <Type Name="tblAnswer">
      <Column Name="answernr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="answer" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="answer_linkanswer" Member="tblLinkAnswers" ThisKey="answernr" OtherKey="answernr" Type="tblLinkAnswer" />
      <Association Name="answer_question" Member="tblQuestions" ThisKey="answernr" OtherKey="correctanswernr" Type="tblQuestion" />
    </Type>
  </Table>
  <Table Name="dbo.teacher" Member="tblTeachers">
    <Type Name="tblTeacher">
      <Column Name="teachernr" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="teacher_questionnaire" Member="tblQuestionnaires" ThisKey="teachernr" OtherKey="teachernr" Type="tblQuestionnaire" />
    </Type>
  </Table>
  <Table Name="dbo.linkanswer" Member="tblLinkAnswers">
    <Type Name="tblLinkAnswer">
      <Column Name="linkanswernr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="questionnr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[index]" Member="index" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="answernr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="linkanswer_linkresult" Member="tblLinkResults" ThisKey="linkanswernr" OtherKey="linkanswernr" Type="tblLinkResult" />
      <Association Name="answer_linkanswer" Member="tblAnswer" ThisKey="answernr" OtherKey="answernr" Type="tblAnswer" IsForeignKey="true" />
      <Association Name="question_linkanswer" Member="tblQuestion" ThisKey="questionnr" OtherKey="questionnr" Type="tblQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.linkresult" Member="tblLinkResults">
    <Type Name="tblLinkResult">
      <Column Name="resultnr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="linkanswernr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="studentnr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="linkanswer_linkresult" Member="tblLinkAnswer" ThisKey="linkanswernr" OtherKey="linkanswernr" Type="tblLinkAnswer" IsForeignKey="true" />
      <Association Name="result_linkresult" Member="tblResult" ThisKey="resultnr" OtherKey="resultnr" Type="tblResult" IsForeignKey="true" />
      <Association Name="student_linkresult" Member="tblStudent" ThisKey="studentnr" OtherKey="studentnr" Type="tblStudent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.question" Member="tblQuestions">
    <Type Name="tblQuestion">
      <Column Name="questionnr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="question" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="correctanswernr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="question_linkanswer" Member="tblLinkAnswers" ThisKey="questionnr" OtherKey="questionnr" Type="tblLinkAnswer" />
      <Association Name="tblQuestion_linkquestion" Member="tblLinkQuestions" ThisKey="questionnr" OtherKey="questionnr" Type="tblLinkQuestion" />
      <Association Name="answer_question" Member="tblAnswer" ThisKey="correctanswernr" OtherKey="answernr" Type="tblAnswer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.questionnaire" Member="tblQuestionnaires">
    <Type Name="tblQuestionnaire">
      <Column Name="questionnairenr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="questionnairename" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="teachernr" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="questionnaire_exam" Member="tblExams" ThisKey="questionnairenr" OtherKey="questionnairenr" Type="tblExam" />
      <Association Name="tblQuestionnaire_linkquestion" Member="tblLinkQuestions" ThisKey="questionnairenr" OtherKey="questionnairenr" Type="tblLinkQuestion" />
      <Association Name="teacher_questionnaire" Member="tblTeacher" ThisKey="teachernr" OtherKey="teachernr" Type="tblTeacher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.result" Member="tblResults">
    <Type Name="tblResult">
      <Column Name="resultnr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="examnr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="result_linkresult" Member="tblLinkResults" ThisKey="resultnr" OtherKey="resultnr" Type="tblLinkResult" />
      <Association Name="exam_result" Member="tblExam" ThisKey="examnr" OtherKey="examnr" Type="tblExam" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.student" Member="tblStudents">
    <Type Name="tblStudent">
      <Column Name="studentnr" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="groupnr" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="student_linkresult" Member="tblLinkResults" ThisKey="studentnr" OtherKey="studentnr" Type="tblLinkResult" />
    </Type>
  </Table>
  <Table Name="dbo.exam" Member="tblExams">
    <Type Name="tblExam">
      <Column Name="examnr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="questionnairenr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="starttime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="endtime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="groupnr" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="exam_result" Member="tblResults" ThisKey="examnr" OtherKey="examnr" Type="tblResult" />
      <Association Name="questionnaire_exam" Member="tblQuestionnaire" ThisKey="questionnairenr" OtherKey="questionnairenr" Type="tblQuestionnaire" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.linkquestion" Member="tblLinkQuestions">
    <Type Name="tblLinkQuestion">
      <Column Name="questionnairenr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="questionnr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Member="linkquestionnr" AutoSync="Never" Type="System.String" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="tblQuestionnaire_linkquestion" Member="tblQuestionnaire" ThisKey="questionnairenr" OtherKey="questionnairenr" Type="tblQuestionnaire" IsForeignKey="true" />
      <Association Name="tblQuestion_linkquestion" Member="tblQuestion" ThisKey="questionnr" OtherKey="questionnr" Type="tblQuestion" IsForeignKey="true" />
    </Type>
  </Table>
</Database>